name: Update flake.lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
#- cron: "30 2/6 * * *" # not to frequent, GitHub only allows a few pulls per hour

permissions:
  contents: write

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # https://nix.dev/guides/recipes/continuous-integration-github-actions
      - uses: cachix/cachix-action@v14
        with:
          name: mrvandalo-taskwarrior
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: update nix flakes
        run: nix flake update

      - name: nix build bugwarrior
        run: nix build .#bugwarrior | cachix push mrvandalo-taskwarrior

      - name: nix build tasksh
        run: nix build .#tasksh | cachix push mrvandalo-taskwarrior

      - name: nix build taskwarrior-hooks
        run: nix build .#taskwarrior-hooks | cachix push mrvandalo-taskwarrior

      - name: commit & push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Forgejo Action :robot:"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m ":arrow_up: nix flake update"
            git push
          else
            echo "No changes to commit"
          fi
